### ISSUE TITLE
about Flights Live Pricing

### ISSUE THREAD

**Issue by kodmanyagha** [ozdemirburak/skyscanner-php#3]
I'm getting that error: Rate limit has been exceeded: 0 PerMinute for PricingSession

What do youthink?

**Comment by ozdemirburak** [comment]
Probably it's because of the situation that Flights Live Pricing service is currently suspended. See the post here: https://support.business.skyscanner.net/hc/en-us/articles/206800359-Which-services-can-I-access-and-what-are-the-rate-limits-

You need to use the BrowseCache method, at least for now.

**Comment by ozdemirburak** [comment]
They opened the Flights Live Pricing service again. 

If you still have that issue, please feel free to re-open this one.
